spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://plugger.postgres.database.azure.com:5432/db_fw_partnership_service?user=plugger&password=password123-&sslmode=require
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: 'true'
      ddl-auto: update
  security:
    user:
      name: user
      password: password
  application:
    name: fw-partnership-service
eureka:
  client:
    serviceUrl:
      defaultZone: https://fw-discovery-server.azurewebsites.net/eureka
  instance:
    hostname: fw-partnership-service.azurewebsites.net
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}
security:
  user:
    password: ${eureka.password}

server:
  error:
    include-message: always

app:
  services:
    payment:
      url: https://fw-payment-service.azurewebsites.net
    auth:
      url: https://fw-auth-service.azurewebsites.net
    file:
      url: https://fw-file-service.azurewebsites.net